- name: Configure nginx 
  hosts: all
  become: true
  tasks:
    - name: Install Nginx
      yum: 
        name: httpd
        state: latest

    - name: Create directory
      file:
        path: /usr/share/httpd/html
        state: directory
        
    - name: Copy index.html
      copy:
        src: index.html
        dest: /usr/share/httpd/html/index.html

    - name: Restart nginx
      service:
        name: nginx
        state: restarted
