- name: Configure nginx 
  hosts: all
  become: true
  tasks:
    - name: Install Nginx
      yum: 
        name: httpd
        state: latest
    
    - name: Copy index.html
      copy:
        src: index.html
        dest: /usr/share/nginx/html/index.html

    - name: Restart nginx
      service:
        name: nginx
        state: restarted
